---

# install nginx

- name: install nginx
  become: yes
  portage: package=www-servers/nginx state=emerged newuse=yes update=yes


# configure nginx

- name: ensure required directories are present
  become: yes
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0755"
  with_items:
    - path: "/etc/nginx/sites.d"
      owner: "{{ nginx_user }}"
      group: "root"
      mode: "0755"
    - path: "/etc/nginx/upstreams.d"
      owner: "{{ nginx_user }}"
      group: "root"
      mode: "0755"
    - path: "var/log/nginx"
      owner: "{{ nginx_user }}"
      group: "root"
      mode: "0755"

- name: write nginx config
  become: yes
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  notify: nginx - restart


# post tasks

- name: ensure service is running
  become: yes
  service: name=nginx state=started enabled=yes
